### ISSUE TITLE
Info lost on reload

### ISSUE THREAD

**Issue by brandonpilane** [i-Bex/boxshadowcraft#1]
<h2> The Problem: </h2>
Hi @i-Bex ,<br><br>When viewing the site i accidentally reloaded it and notice that all the information was lost. 😔 
<br><br>
It would be really handy to convert all the information from variables (etc) to a .json file that could be stored locally(or otherwise) so that in cases like that the problem is avoided. 😊 
<br><hr><br>
This is otherwise this is a pretty good site.👏🏾
<br>
I know its been <strong>months</strong> since you've worked on this but i thought i might share this anyway.

**Comment by ABottleOfSprite** [comment]
If you don't mind by the way I'd love to help🫡, I'll open a pull request.<br><br>
I'm only a <i>few weeks</i> into learning front end, but id love to help and maybe I'll learn a thing or two.🫤😓

**Comment by brandonpilane** [comment]
If you don't mind by the way I'd love to help🫡, I'll open a pull request.<br><br>
I'm only a <i>few weeks</i> into learning front end, but id love to help and maybe I'll learn a thing or two.🫤😓
<br><hr><br>
Didnt mean to close the issue.🫠

**Comment by zshaian** [comment]
Hi @ABottleOfSprite, thank you for bringing up this issue. I wanted to let you know that I'm considering using React for this project, as I'm currently in the process of learning it. With this change, I anticipate being able to address the concerns raised in your issue more effectively. Additionally, I'll be refactoring a lot of the existing code, which should improve its maintainability and readability. I also plan to introduce new UI elements and features to enhance the overall user experience. Your input is valuable, and I'll make sure to keep you updated on the progress. Thanks again for your contribution to the project!

**Comment by brandonpilane** [comment]
No problem @i-Bex . I wish i could have contributed more, but i was a little overwhelmed with the amount of work it would take. Good luck with learning React.😊🤙
